import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';

import { rawText } from '../src/data';
import { app } from '../src/index';

describe('factor release artifact API', () => {
  it('serves exact generated bytes covered by the manifest', async () => {
    const manifestResponse = await app.request('/v1/manifest');
    expect(await manifestResponse.text()).toBe(rawText.manifest);

    const manifest = JSON.parse(rawText.manifest) as {
      release_format_version: number;
      factor_schema_version: number;
      files: { path: string; sha256: string; bytes: number }[];
    };
    expect(manifest.release_format_version).toBe(1);
    expect(manifest.factor_schema_version).toBe(1);

    const response = await app.request('/v1/factors/food_owid_proxy');
    const text = await response.text();
    const metadata = manifest.files.find((file) => file.path === 'food_owid_proxy.json')!;
    expect(text).toBe(rawText.food_owid_proxy);
    expect(Buffer.byteLength(text, 'utf8')).toBe(metadata.bytes);
    expect(createHash('sha256').update(text, 'utf8').digest('hex')).toBe(metadata.sha256);
  });
});
